lib/taskmaster_web/router.ex
defmodule TaskmasterWeb.Router do
  use TaskmasterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskmasterWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskmasterWeb.Plugs.FetchSession # FIXME: "FetchUser"
  end

  scope "/ajax", TaskmasterWeb do
    pipe_through :ajax
    resources "/time-blocks", TimeBlockController
  end

  scope "/", TaskmasterWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController do
      get "/report", UserController, :report, as: :report
    end
    resources "/tasks", TaskController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskmasterWeb do
  #   pipe_through :api
  # end
end

lib/taskmaster/users/user.ex
defmodule Taskmaster.Users.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :username, :string

    belongs_to :manager, Taskmaster.Users.User
    has_many :managees, Taskmaster.Users.User, foreign_key: :manager_id
    has_many :tasks, Taskmaster.Tasks.Task, foreign_key: :assignee_id

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:username, :manager_id])
    |> validate_required([:username])
    |> unique_constraint(:username)
  end
end

lib/taskmaster/users/users.ex
defmodule Taskmaster.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias Taskmaster.Repo

  alias Taskmaster.Users.User

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id) do Repo.get!(User, id) |> Repo.preload(:manager) end
  def get_user(id) do Repo.get(User, id) |> Repo.preload(:manager) end

  def get_user_by_username(username), do: Repo.get_by(User, username: username)

  # Lists the managees of a user with provided id. If the user does not exist, returns nil.
  def list_user_managees(id) do
    user = Repo.get(User, id)
    if user do
      user = Repo.preload(user, :managees)
      user.managees
    else
      nil
    end
  end

  def list_user_tasks(id) do
    user = Repo.get(User, id)
    if user do
      user = Repo.preload(user, [tasks: :time_blocks])
      user.tasks
    else
      nil
    end
  end

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a User.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{source: %User{}}

  """
  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end

  @doc """
    Return whether the user with the given id exists.
  """
  def user_exists(id) do
    Repo.get(User, id) != nil
  end
end

lib/taskmaster_web/controllers/user_controller.ex
defmodule TaskmasterWeb.UserController do
  use TaskmasterWeb, :controller

  alias Taskmaster.Users
  alias Taskmaster.Users.User

  def index(conn, _params) do
    users = Users.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Users.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Users.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    managees = Users.list_user_managees(id)
    current_user = conn.assigns[:current_user]
    current_user_id = if current_user do current_user.id else nil end
    set_as_manager_cset = Users.change_user(%User{ id: current_user_id, manager_id: id })
    render(conn, "show.html", user: user, managees: managees, set_as_manager_cset: set_as_manager_cset)
  end

  def report(conn, %{"user_id" => id}) do
    user = Users.get_user!(id)
    tasks =  Users.list_user_tasks(id)
    render(conn, "report.html", tasks: tasks, user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    changeset = Users.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)
    case Users.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    {:ok, _user} = Users.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/taskmaster_web/views/user_view.ex
defmodule TaskmasterWeb.UserView do
  use TaskmasterWeb, :view

  #def render("report.html", _assigns) do
  #  "Meow"
  #end
end

lib/taskmaster_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index), class: "btn btn-primary" %></span>

lib/taskmaster_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div>
    <%= submit "Create", class: "btn btn-primary mb-3" %>
  </div>
<% end %>

lib/taskmaster_web/templates/user/index.html.eex
<h1>User List</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td>
        <%= link "Profile", to: Routes.user_path(@conn, :show, user), class: "btn btn-secondary" %>
      <%= if @current_user && @current_user.username == "admin" && user.username != "admin" do %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user),
        method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-secondary" %>
      <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/taskmaster_web/templates/user/new.html.eex
<h1>Register an Account</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Cancel", to: Routes.page_path(@conn, :index), class: "btn btn-primary" %></span>

lib/taskmaster_web/templates/user/report.html.eex
<%= if @user do %>
  <h1><%= @user.username %>'s Task Report</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Completed</th>
        <th>Time Spent</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= for task <- @tasks do %>
        <tr>
          <td><%= task.title %></td>
          <td><%= if task.completed do "☑" else "☐" end %></td>
          <td><%= TaskmasterWeb.TaskView.calculate_time_spent(task) %></td>
          <td><%= link "Show", to: Routes.task_path(@conn, :show, task), class: "btn btn-secondary" %></td>
        </tr>
      <% end %>
    </body>
  </table>
<% end %>

lib/taskmaster_web/templates/user/show.html.eex
<h3><%= @user.username %>'s Profile</h3>

<h4><strong>Manager:</strong>
<%= if @user.manager do @user.manager.username end %>
</h4>

<%= if @user.manager != nil do %>
  <%= link "Manager Profile", to: Routes.user_path(@conn, :show, @user.manager), class: "btn btn-primary mb-3" %>
  <%= if @current_user && @current_user.id == @user.id do %>
    <%= form_for @set_as_manager_cset, Routes.user_path(@conn, :update, @current_user), [method: :put], fn f -> %>
      <%= hidden_input f, :id %>
      <%= hidden_input f, :manager_id, value: nil %>

      <%= submit "Leave Manager", class: "btn btn-secondary mb-3" %>
    <% end %>
  <% end %>
<% end %>

<h3>Underlings</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for user <- @managees do %>
      <tr>
        <td><%= user.username %></td>
        <td>
          <%= link "Profile", to: Routes.user_path(@conn, :show, user), class: "btn btn-primary" %>
          <%= if @current_user && @current_user.id == @user.id do %>
            <%= link "Task Report", to: Routes.user_report_path(@conn, :report, user), class: "btn btn-secondary" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </body>
</table>

<%= if @current_user && @current_user.id != @user.id && @current_user.manager_id != @user.id do %>
  <%= form_for @set_as_manager_cset, Routes.user_path(@conn, :update, @current_user), [method: :put], fn f -> %>
    <%= hidden_input f, :id %>
    <%= hidden_input f, :manager_id %>

    <%= submit "Become Underling", class: "btn btn-primary mb-3" %>
  <% end %>
<% end %>

<span><%= link "Back", to: Routes.user_path(@conn, :index), class: "btn btn-primary" %></span>